# Generated by Django 5.1.1 on 2024-09-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id'], 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
    ]
